### ISSUE TITLE
Latest release 0.4.0?

### ISSUE THREAD

**Issue by slavkoja** [inveniosoftware/flask-menu#61]
On the releases page (https://github.com/inveniosoftware/flask-menu/releases) is by default as latest release marked 0.4.0 verion. One need to click on the "Show 3 newer tags" link to show 0.6.0 version. Who do not know what is latest version can be mistaken and use old release.

**Comment by jirikuncar** [comment]
@slavkoja thank you for letting us know. We hope to automatize the release process so the GitHub is up-to-date with PyPI (https://pypi.org/project/Flask-Menu/) in the future.

**Comment by lnielsen** [comment]
I've now deleted the release information so that it clearly shows the latest tags. As @jirikuncar says, PyPI is the place to get the information about the latest releases. We may automate the release notes publishing to GitHub in the future, but at least until then, the release page is not misleading.
